name: Upload dotnet package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_TOKEN}}
      - run: dotnet build --configuration Release /src/OpenTracing.Contrib.MongoDB/OpenTracing.Contrib.MongoDB.csproj
      - name: Create the package
        run: dotnet pack --configuration Release /src/OpenTracing.Contrib.MongoDB/OpenTracing.Contrib.MongoDB.csproj
      - name: Publish the package to GPR
        run: dotnet nuget push /src/OpenTracing.Contrib.MongoDB/bin/Release/*.nupkg
